#!/usr/bin/env node
// Regenerate src/generated-version.ts from package.json's "version" field.
//
// Run automatically before `pnpm build`. Also runnable by hand:
//   pnpm gen:version
//
// The generated file is COMMITTED to the repo so a fresh checkout
// typechecks without a build step. The pre-build hook keeps it in
// sync. `verify:version` (run in CI) fails if a contributor bumps
// package.json but forgets to commit the regenerated file.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(__dirname, '..', 'package.json');
const outPath = resolve(__dirname, '..', 'src', 'generated-version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
const version = pkg.version;

if (typeof version !== 'string' || !version) {
  console.error(`gen-version: package.json has no "version" field: ${pkgPath}`);
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/gen-version.mjs. Do not edit.
// Regenerate with \`pnpm gen:version\` (or it runs automatically before \`pnpm build\`).
export const VERSION = ${JSON.stringify(version)} as const;
`;

writeFileSync(outPath, content);
console.log(`gen-version: wrote ${outPath} (version=${version})`);
